name = "MyServer"
author = "Chlorodose"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6fce9f668e47234f9a339ea23cd7dbe46c939dc99bd09f0022f6930bdaf26ae"

[versions]
fabric = "0.16.10"
minecraft = "1.18.2"
