name = "MyServer"
author = "Chlorodose"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61e66d5a1e2f4954245c53438435b2d0a3133aa0bc8fb3b371e7d38c7e330320"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
